### ISSUE TITLE
Rankingとトップページの関係

### ISSUE THREAD

**Issue by Eri-0910** [yot-sailing/YOT-novel#15]
- Topページを開くとヘッダーがなぜかランキングの部分も色が変わっている

- フッターのランキングをクリックしてもトップページに行く

リンクがうまく貼れていない？気がするので調査

**Comment by mimimimizuki** [comment]
topページを開くてランキングの部分も色変わっているのは修正済み

**Comment by mimimimizuki** [comment]
フッターのやつも修正しました、mizuki_branchで編集してしまったけどFooter.jsを他にいじる人いたらそっちで変更して欲しいかも。Footer.js 35行目のlink先をrankingにするだけです
